### ISSUE TITLE
/open pr doesn't link to the issue it closes anymore.

### ISSUE THREAD

**Issue by rimrul** [git-for-windows/gfw-helper-github-app#18] opened 2022-12-31 12:58 UTC
It used to do that (see https://github.com/git-for-windows/MSYS2-packages/pull/71#issue-1505887299), but does not do so anymore (see https://github.com/git-for-windows/MSYS2-packages/pull/72#issue-1510034720)

**Comment by dscho** [comment] 2023-01-01 19:45
But the latter wasn't merged, was it? And please note the the first one had "This closes git-for-windows/git#4191" in its initial comment...

**Comment by dscho** [comment] 2023-01-01 22:10
Ah. I think I know the root cause. [This code](https://github.com/git-for-windows/git-for-windows-automation/blob/a538b16263ff442be4729cf990f1bf4001e5dc6c/.github/workflows/open-pr.yml#L189-L193) tries to determine whether there is any `component-update` ticket that could be closed by the opened PR.

Note that it looks for the exact version in the title. _Without leading `v`_, [except for Git LFS](https://github.com/git-for-windows/git-for-windows-automation/blob/a538b16263ff442be4729cf990f1bf4001e5dc6c/.github/workflows/open-pr.yml#L183).

I guess it would be better to be lenient and try the version without leading `v` first, and if there are no hits, dig deeper. Or maybe an "OR" works? A quick test:

- ["[New libcbor version]" 0.10.1 in:title type:issue repo:git-for-windows/git state:open author:app/github-actions label:component-update](https://github.com/search?q=%22%5BNew%20libcbor%20version%5D%22%200.10.1%20in%3Atitle%20type%3Aissue%20repo%3Agit-for-windows%2Fgit%20state%3Aopen%20author%3Aapp%2Fgithub-actions%20label%3Acomponent-update&type=issues) does not find the ticket, but
- ["[New libcbor version]" (0.10.1 OR v0.10.1) in:title type:issue repo:git-for-windows/git state:open author:app/github-actions label:component-update](https://github.com/search?q=%22%5BNew+libcbor+version%5D%22+%280.10.1+OR+v0.10.1%29+in%3Atitle+type%3Aissue+repo%3Agit-for-windows%2Fgit+state%3Aopen+author%3Aapp%2Fgithub-actions+label%3Acomponent-update&type=issues) does

So I guess what we want is this:

```diff
diff --git a/.github/workflows/open-pr.yml b/.github/workflows/open-pr.yml
index 6bb1b7a..1b6b889 100644
--- a/.github/workflows/open-pr.yml
+++ b/.github/workflows/open-pr.yml
@@ -180,7 +180,7 @@ jobs:
             let body = ''
             try {
               const name = process.env.PACKAGE_TO_UPGRADE
-              const version = `${name.match(/git-lfs/) ? 'v' : ''}${process.env.UPGRADE_TO_VERSION}`
+              const version = process.env.UPGRADE_TO_VERSION
 
               if (name === 'mintty') body = `See https://github.com/mintty/mintty/releases/tag/${version} for details.`
               else if (name === 'mingw-w64-git-lfs') body = `See https://github.com/git-lfs/git-lfs/releases/tag/${version} for details.`
@@ -188,7 +188,7 @@ jobs:
 
               const terms = 'type:issue repo:git-for-windows/git state:open author:app/github-actions label:component-update'
               const { data } = await github.rest.search.issuesAndPullRequests({
-                q: `"[New ${name.replace(/^mingw-w64-/, '')} version]" ${version} in:title ${terms}`,
+                q: `"[New ${name.replace(/^mingw-w64-/, '')} version]" (${version} OR v${version}) in:title ${terms}`,
               })
               if (data.total_count) body = `${body ? `${body}\n\n` : ''}This closes ${data.items[0].html_url}`
             } catch (e) {
```

**Comment by dscho** [comment] 2023-01-01 22:16
@rimrul and [here](https://github.com/git-for-windows/git-for-windows-automation/pull/9) is the Pull Request that throws in a commit message with that diff.

**Comment by dscho** [comment] 2023-01-26 23:07
This should be fixed via https://github.com/git-for-windows/git-for-windows-automation/pull/9.

**Closed by dscho** 2023-01-26 23:07 UTC
